[package]
name = "tauri-runtime-wry"
version = "0.3.3"
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Wry bindings to the Tauri runtime"
edition = "2021"
rust-version = "1.57"
exclude = [ ".license_template", "CHANGELOG.md", "/target" ]
readme = "README.md"

[dependencies]
wry = { version = "0.13.3", default-features = false, features = [ "file-drop", "protocol" ] }
tauri-runtime = { version = "0.3.3", path = "../tauri-runtime" }
tauri-utils = { version = "1.0.0-rc.3", path = "../tauri-utils" }
uuid = { version = "0.8.2", features = [ "v4" ] }
infer = "0.4"

[target."cfg(windows)".dependencies]
ico = "0.1"
webview2-com = "0.13.0"

  [target."cfg(windows)".dependencies.windows]
  version = "0.30.0"
  features = [ "Win32_Foundation" ]

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
png = "0.16"
gtk = { version = "0.15", features = [ "v3_20" ] }

[features]
dox = [ "wry/dox" ]
devtools = [ "wry/devtool", "tauri-runtime/devtools" ]
system-tray = [ "wry/tray", "tauri-runtime/system-tray" ]
macos-private-api = [
  "wry/fullscreen",
  "wry/transparent",
  "tauri-runtime/macos-private-api"
]
objc-exception = [ "wry/objc-exception" ]
