[package]
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "web-programming" ]
description = "Make tiny, secure apps for all desktop platforms with Tauri"
edition = "2021"
rust-version = "1.57"
exclude = [
  "/test",
  "/.scripts",
  ".license_template",
  "CHANGELOG.md",
  "/target"
]
homepage = "https://tauri.studio"
license = "Apache-2.0 OR MIT"
name = "tauri"
readme = "README.md"
repository = "https://github.com/tauri-apps/tauri"
version = "1.0.0-rc.4"

[package.metadata.docs.rs]
no-default-features = true
features = [
  "wry",
  "__isolation-docs",
  "custom-protocol",
  "api-all",
  "cli",
  "__updater-docs",
  "system-tray",
  "devtools",
  "dox"
]
rustdoc-args = [ "--cfg", "doc_cfg" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin"
]

[package.metadata.cargo-udeps.ignore]
normal = [ "attohttpc" ]

[dependencies]
serde_json = { version = "1.0", features = [ "raw_value" ] }
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "1.16", features = [ "rt", "rt-multi-thread", "sync", "fs", "io-util" ] }
futures = "0.3"
uuid = { version = "0.8", features = [ "v4" ] }
url = { version = "2.2" }
anyhow = "1.0"
thiserror = "1.0"
once_cell = "1.9"
tauri-runtime = { version = "0.3.3", path = "../tauri-runtime" }
tauri-macros = { version = "1.0.0-rc.3", path = "../tauri-macros" }
tauri-utils = { version = "1.0.0-rc.3", path = "../tauri-utils" }
tauri-runtime-wry = { version = "0.3.3", path = "../tauri-runtime-wry", optional = true }
rand = "0.8"
semver = "1.0"
serde_repr = "0.1"
state = "0.5"
tar = "0.4"
tempfile = "3"
zip = { version = "0.5", optional = true }
ignore = "0.4"
either = "1.6"
flate2 = "1.0"
http = "0.2"
bincode = "1.3"
dirs-next = "2.0"
percent-encoding = "2.1"
base64 = { version = "0.13", optional = true }
clap = { version = "3", optional = true }
notify-rust = { version = "4.5", optional = true }
reqwest = { version = "0.11", features = [ "json", "multipart" ], optional = true }
bytes = { version = "1", features = [ "serde" ], optional = true }
attohttpc = { version = "0.18", features = [ "json", "form" ], optional = true }
open = { version = "2.0", optional = true }
shared_child = { version = "1.0", optional = true }
os_pipe = { version = "1.0", optional = true }
memchr = { version = "2.4", optional = true }
rfd = { version = "0.7.0", features = [ "parent" ], optional = true }
raw-window-handle = "0.4.2"
minisign-verify = { version = "0.2", optional = true }
os_info = { version = "3.2.0", optional = true }
futures-lite = "1.12"
regex = { version = "1.5", optional = true }
glob = "0.3"
data-url = { version = "0.1", optional = true }
serialize-to-javascript = "=0.1.1"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = { version = "0.15", features = [ "v3_20" ] }
glib = "0.15"

[target."cfg(target_os = \"macos\")".dependencies]
embed_plist = "1.2"

[target."cfg(windows)".dev-dependencies.windows]
version = "0.30.0"
features = [ "Win32_Foundation" ]

[build-dependencies]
cfg_aliases = "0.1.1"

[dev-dependencies]
mockito = "0.30"
proptest = "1.0.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tauri = { path = ".", default-features = false, features = [ "wry" ] }
tokio-test = "0.4.2"
tokio = { version = "1.16", features = [ "full" ] }

[features]
default = [ "wry", "compression", "objc-exception" ]
compression = [ "tauri-macros/compression", "tauri-utils/compression" ]
wry = [ "tauri-runtime-wry" ]
objc-exception = [ "tauri-runtime-wry/objc-exception" ]
isolation = [ "tauri-utils/isolation", "tauri-macros/isolation" ]
__isolation-docs = [
  "tauri-utils/__isolation-docs",
  "tauri-macros/__isolation-docs"
]
custom-protocol = [ "tauri-macros/custom-protocol" ]
updater = [
  "minisign-verify",
  "base64",
  "http-api",
  "dialog-ask",
  "fs-extract-api"
]
__updater-docs = [ "minisign-verify", "base64", "http-api", "dialog-ask" ]
http-api = [ "attohttpc" ]
shell-open-api = [ "open", "regex", "tauri-macros/shell-scope" ]
fs-extract-api = [ "zip" ]
reqwest-client = [ "reqwest", "bytes" ]
command = [ "shared_child", "os_pipe", "memchr" ]
dialog = [ "rfd" ]
notification = [ "notify-rust" ]
cli = [ "clap" ]
system-tray = [ "tauri-runtime/system-tray", "tauri-runtime-wry/system-tray" ]
devtools = [ "tauri-runtime/devtools", "tauri-runtime-wry/devtools" ]
dox = [ "tauri-runtime-wry/dox" ]
macos-private-api = [
  "tauri-runtime/macos-private-api",
  "tauri-runtime-wry/macos-private-api"
]
window-data-url = [ "data-url" ]
api-all = [
  "clipboard-all",
  "dialog-all",
  "fs-all",
  "global-shortcut-all",
  "http-all",
  "notification-all",
  "os-all",
  "path-all",
  "process-all",
  "protocol-all",
  "shell-all",
  "window-all"
]
clipboard-all = [ "clipboard-write-text", "clipboard-read-text" ]
clipboard-read-text = [ ]
clipboard-write-text = [ ]
dialog-all = [ "dialog-open", "dialog-save", "dialog-message", "dialog-ask" ]
dialog-ask = [ "dialog" ]
dialog-confirm = [ "dialog" ]
dialog-message = [ "dialog" ]
dialog-open = [ "dialog" ]
dialog-save = [ "dialog" ]
fs-all = [
  "fs-copy-file",
  "fs-create-dir",
  "fs-read-file",
  "fs-read-dir",
  "fs-remove-dir",
  "fs-remove-file",
  "fs-rename-file",
  "fs-write-file"
]
fs-copy-file = [ ]
fs-create-dir = [ ]
fs-read-file = [ ]
fs-read-dir = [ ]
fs-remove-dir = [ ]
fs-remove-file = [ ]
fs-rename-file = [ ]
fs-write-file = [ ]
global-shortcut-all = [ ]
http-all = [ "http-request" ]
http-request = [ "http-api" ]
notification-all = [ "notification", "dialog-ask" ]
os-all = [ "os_info" ]
path-all = [ ]
process-all = [ "process-relaunch", "process-exit" ]
process-exit = [ ]
process-relaunch = [ ]
process-relaunch-dangerous-allow-symlink-macos = [ "tauri-utils/process-relaunch-dangerous-allow-symlink-macos" ]
protocol-all = [ "protocol-asset" ]
protocol-asset = [ ]
shell-all = [ "shell-execute", "shell-sidecar", "shell-open" ]
shell-execute = [ "command", "regex", "tauri-macros/shell-scope" ]
shell-sidecar = [ "command", "regex", "tauri-macros/shell-scope" ]
shell-open = [ "shell-open-api" ]
window-all = [
  "window-create",
  "window-center",
  "window-request-user-attention",
  "window-set-resizable",
  "window-set-title",
  "window-maximize",
  "window-unmaximize",
  "window-minimize",
  "window-unminimize",
  "window-show",
  "window-hide",
  "window-close",
  "window-set-decorations",
  "window-set-always-on-top",
  "window-set-size",
  "window-set-min-size",
  "window-set-max-size",
  "window-set-position",
  "window-set-fullscreen",
  "window-set-focus",
  "window-set-icon",
  "window-set-skip-taskbar",
  "window-start-dragging",
  "window-print"
]
window-create = [ ]
window-center = [ ]
window-request-user-attention = [ ]
window-set-resizable = [ ]
window-set-title = [ ]
window-maximize = [ ]
window-unmaximize = [ ]
window-minimize = [ ]
window-unminimize = [ ]
window-show = [ ]
window-hide = [ ]
window-close = [ ]
window-set-decorations = [ ]
window-set-always-on-top = [ ]
window-set-size = [ ]
window-set-min-size = [ ]
window-set-max-size = [ ]
window-set-position = [ ]
window-set-fullscreen = [ ]
window-set-focus = [ ]
window-set-icon = [ ]
window-set-skip-taskbar = [ ]
window-start-dragging = [ ]
window-print = [ ]
config-json5 = [ "tauri-macros/config-json5" ]

[[example]]
name = "commands"
path = "../../examples/commands/src-tauri/src/main.rs"

[[example]]
name = "helloworld"
path = "../../examples/helloworld/src-tauri/src/main.rs"

[[example]]
name = "multiwindow"
path = "../../examples/multiwindow/src-tauri/src/main.rs"
required-features = [ "window-create" ]

[[example]]
name = "navigation"
path = "../../examples/navigation/src-tauri/src/main.rs"
required-features = [ "window-create" ]

[[example]]
name = "splashscreen"
path = "../../examples/splashscreen/src-tauri/src/main.rs"

[[example]]
name = "state"
path = "../../examples/state/src-tauri/src/main.rs"

[[example]]
name = "streaming"
path = "../../examples/streaming/src-tauri/src/main.rs"

[[example]]
name = "isolation"
path = "../../examples/isolation/src-tauri/src/main.rs"
required-features = [ "isolation" ]
