workspace = { }

[package]
name = "tauri-bundler"
version = "1.0.0-rc.3"
authors = [
  "George Burton <burtonageo@gmail.com>",
  "Tauri Programme within The Commons Conservancy"
]
categories = [ "command-line-utilities", "development-tools::cargo-plugins" ]
license = "Apache-2.0 OR MIT"
keywords = [ "bundle", "cargo", "tauri" ]
repository = "https://github.com/tauri-apps/tauri"
description = "Wrap rust executables in OS-specific app bundles for Tauri"
edition = "2021"
rust-version = "1.57"
exclude = [
  ".license_template",
  "CHANGELOG.md",
  "/target",
  "rustfmt.toml"
]

[dependencies]
tauri-utils = { version = "1.0.0-rc.3", path = "../../core/tauri-utils", features = [ "resources" ] }
ar = "0.9.0"
icns = "0.3"
image = "0.24.1"
libflate = "1.1"
md5 = "0.7.0"
anyhow = "1.0"
thiserror = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
strsim = "0.10.0"
tar = "0.4"
termcolor = "1.1.2"
toml = "0.5.8"
walkdir = "2"
handlebars = { version = "4.2" }
zip = { version = "0.5" }
tempfile = "3.3.0"
os_pipe = "1"

[target."cfg(target_os = \"windows\")".dependencies]
attohttpc = "0.18"
uuid = { version = "0.8", features = [ "v4", "v5" ] }
bitness = "0.4"
winreg = "0.10"
sha2 = "0.10"
hex = "0.4"
glob = "0.3"

[target."cfg(target_os = \"macos\")".dependencies]
time = { version = "0.3", features = [ "formatting" ] }
dirs-next = "2.0"

[target."cfg(any(target_os = \"macos\", target_os = \"windows\"))".dependencies]
regex = "1"

[target."cfg(target_os = \"linux\")".dependencies]
heck = "0.4"

[lib]
name = "tauri_bundler"
path = "src/lib.rs"
